2022-03-28 12:03:42,320 INFO    MainThread:12299 [wandb_setup.py:_flush():75] Loading settings from /Users/AFischer/.config/wandb/settings
2022-03-28 12:03:42,320 INFO    MainThread:12299 [wandb_setup.py:_flush():75] Loading settings from /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/settings
2022-03-28 12:03:42,320 INFO    MainThread:12299 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-28 12:03:42,320 INFO    MainThread:12299 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-28 12:03:42,320 INFO    MainThread:12299 [wandb_init.py:_log_setup():405] Logging user logs to /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/run-20220328_120342-ofd110xp/logs/debug.log
2022-03-28 12:03:42,320 INFO    MainThread:12299 [wandb_init.py:_log_setup():406] Logging internal logs to /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/run-20220328_120342-ofd110xp/logs/debug-internal.log
2022-03-28 12:03:42,320 INFO    MainThread:12299 [wandb_init.py:init():439] calling init triggers
2022-03-28 12:03:42,320 INFO    MainThread:12299 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {}
2022-03-28 12:03:42,321 INFO    MainThread:12299 [wandb_init.py:init():458] re-initializing run, found existing run on stack: 1avpyebf
2022-03-28 12:03:42,322 INFO    MainThread:12299 [wandb_run.py:finish():1539] finishing run afischer/tcn_samp_en-project/1avpyebf
2022-03-28 12:03:42,323 INFO    MainThread:12299 [jupyter.py:save_history():429] not saving jupyter history
2022-03-28 12:03:42,323 INFO    MainThread:12299 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-28 12:03:42,323 INFO    MainThread:12299 [wandb_init.py:_jupyter_teardown():337] cleaning up jupyter logic
2022-03-28 12:03:42,323 INFO    MainThread:12299 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 0
2022-03-28 12:03:42,325 INFO    MainThread:12299 [wandb_run.py:_restore():1674] restore
2022-03-28 12:03:42,574 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 824
  total_bytes: 824
}

2022-03-28 12:03:42,695 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 824
  total_bytes: 824
}

2022-03-28 12:03:42,972 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 824
  total_bytes: 824
}

2022-03-28 12:03:43,975 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 824
  total_bytes: 9273
}

2022-03-28 12:03:44,080 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 824
  total_bytes: 146162
}

2022-03-28 12:03:44,222 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 824
  total_bytes: 146162
}

2022-03-28 12:03:44,330 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 146162
  total_bytes: 146162
}

2022-03-28 12:03:44,440 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 146162
  total_bytes: 146162
}

2022-03-28 12:03:44,553 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 146162
  total_bytes: 146162
}

2022-03-28 12:03:44,660 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 146162
  total_bytes: 146162
}

2022-03-28 12:03:44,772 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 146162
  total_bytes: 146162
}

2022-03-28 12:03:44,879 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 146162
  total_bytes: 146162
}

2022-03-28 12:03:46,168 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 146162
  total_bytes: 146162
}

2022-03-28 12:03:46,813 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 146162
  total_bytes: 146162
}
local_info {
}

2022-03-28 12:03:48,012 INFO    MainThread:12299 [wandb_run.py:_footer_history_summary_info():2865] rendering history
2022-03-28 12:03:48,022 INFO    MainThread:12299 [wandb_run.py:_footer_history_summary_info():2894] rendering summary
2022-03-28 12:03:48,025 INFO    MainThread:12299 [wandb_run.py:_footer_sync_info():2822] logging synced files
2022-03-28 12:03:48,027 INFO    MainThread:12299 [wandb_init.py:init():492] starting backend
2022-03-28 12:03:48,027 INFO    MainThread:12299 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2022-03-28 12:03:48,030 INFO    MainThread:12299 [backend.py:ensure_launched():219] starting backend process...
2022-03-28 12:03:48,054 INFO    MainThread:12299 [backend.py:ensure_launched():224] started backend process with pid: 15812
2022-03-28 12:03:48,056 INFO    MainThread:12299 [wandb_init.py:init():501] backend started and connected
2022-03-28 12:03:48,078 INFO    MainThread:12299 [wandb_run.py:_label_probe_notebook():947] probe notebook
2022-03-28 12:03:48,078 INFO    MainThread:12299 [wandb_run.py:_label_probe_notebook():957] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-03-28 12:03:48,078 INFO    MainThread:12299 [wandb_init.py:init():565] updated telemetry
2022-03-28 12:03:48,109 INFO    MainThread:12299 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-03-28 12:03:49,014 INFO    MainThread:12299 [wandb_run.py:_on_init():1759] communicating current version
2022-03-28 12:03:49,141 INFO    MainThread:12299 [wandb_run.py:_on_init():1763] got version response 
2022-03-28 12:03:49,141 INFO    MainThread:12299 [wandb_init.py:init():625] starting run threads in backend
2022-03-28 12:03:51,078 INFO    MainThread:12299 [wandb_run.py:_console_start():1733] atexit reg
2022-03-28 12:03:51,079 INFO    MainThread:12299 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.WRAP
2022-03-28 12:03:51,079 INFO    MainThread:12299 [wandb_run.py:_redirect():1643] Wrapping output streams.
2022-03-28 12:03:51,079 INFO    MainThread:12299 [wandb_run.py:_redirect():1667] Redirects installed.
2022-03-28 12:03:51,080 INFO    MainThread:12299 [wandb_init.py:init():664] run started, returning control to user process
2022-03-28 12:03:51,080 INFO    MainThread:12299 [wandb_watch.py:watch():47] Watching
2022-03-28 12:06:47,353 INFO    MainThread:12299 [wandb_config.py:__setitem__():153] config set batch_size = 50 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7f83a07aee50>>
2022-03-28 12:06:47,353 INFO    MainThread:12299 [wandb_run.py:_config_callback():992] config_cb batch_size 50 None
2022-03-28 12:06:47,353 INFO    MainThread:12299 [wandb_config.py:__setitem__():153] config set epochs = 45 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7f83a07aee50>>
2022-03-28 12:06:47,353 INFO    MainThread:12299 [wandb_run.py:_config_callback():992] config_cb epochs 45 None
2022-03-28 12:06:47,353 INFO    MainThread:12299 [wandb_config.py:__setitem__():153] config set lr = 0.00011050457699618388 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7f83a07aee50>>
2022-03-28 12:06:47,353 INFO    MainThread:12299 [wandb_run.py:_config_callback():992] config_cb lr 0.00011050457699618388 None
2022-03-28 12:06:47,353 INFO    MainThread:12299 [wandb_config.py:__setitem__():153] config set no_cuda = False - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7f83a07aee50>>
2022-03-28 12:06:47,354 INFO    MainThread:12299 [wandb_run.py:_config_callback():992] config_cb no_cuda False None
2022-03-28 12:06:47,354 INFO    MainThread:12299 [wandb_config.py:__setitem__():153] config set seed = 42 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7f83a07aee50>>
2022-03-28 12:06:47,354 INFO    MainThread:12299 [wandb_run.py:_config_callback():992] config_cb seed 42 None
2022-03-28 12:07:05,865 INFO    MainThread:12299 [wandb_setup.py:_flush():75] Loading settings from /Users/AFischer/.config/wandb/settings
2022-03-28 12:07:05,865 INFO    MainThread:12299 [wandb_setup.py:_flush():75] Loading settings from /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/settings
2022-03-28 12:07:05,865 INFO    MainThread:12299 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-28 12:07:05,865 INFO    MainThread:12299 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-28 12:07:05,865 INFO    MainThread:12299 [wandb_init.py:_log_setup():405] Logging user logs to /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/run-20220328_120705-q3cu5uyi/logs/debug.log
2022-03-28 12:07:05,865 INFO    MainThread:12299 [wandb_init.py:_log_setup():406] Logging internal logs to /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/run-20220328_120705-q3cu5uyi/logs/debug-internal.log
2022-03-28 12:07:05,865 INFO    MainThread:12299 [wandb_init.py:_jupyter_setup():355] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f855a66bac0>
2022-03-28 12:07:05,865 INFO    MainThread:12299 [wandb_init.py:init():439] calling init triggers
2022-03-28 12:07:05,865 INFO    MainThread:12299 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {}
2022-03-28 12:07:05,866 INFO    MainThread:12299 [wandb_init.py:init():458] re-initializing run, found existing run on stack: ofd110xp
2022-03-28 12:07:05,867 INFO    MainThread:12299 [wandb_run.py:finish():1539] finishing run afischer/tcn_samp_en-project/ofd110xp
2022-03-28 12:07:05,867 INFO    MainThread:12299 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 0
2022-03-28 12:07:05,869 INFO    MainThread:12299 [wandb_run.py:_restore():1674] restore
2022-03-28 12:07:06,612 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 824
  total_bytes: 824
}

2022-03-28 12:07:07,177 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 824
  total_bytes: 824
}

2022-03-28 12:07:07,701 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 824
  total_bytes: 169255
}

2022-03-28 12:07:07,817 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 824
  total_bytes: 169255
}

2022-03-28 12:07:07,927 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 824
  total_bytes: 169255
}

2022-03-28 12:07:08,039 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 7295
  total_bytes: 169255
}

2022-03-28 12:07:08,154 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12464
  total_bytes: 169255
}

2022-03-28 12:07:08,261 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 169255
  total_bytes: 169255
}

2022-03-28 12:07:08,376 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 169255
  total_bytes: 169255
}

2022-03-28 12:07:08,487 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 169255
  total_bytes: 169255
}

2022-03-28 12:07:08,602 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 169255
  total_bytes: 169255
}

2022-03-28 12:07:08,713 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 169255
  total_bytes: 169255
}

2022-03-28 12:07:08,827 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 169255
  total_bytes: 169255
}

2022-03-28 12:07:08,940 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 169255
  total_bytes: 169255
}

2022-03-28 12:07:10,191 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 169255
  total_bytes: 169255
}

2022-03-28 12:07:11,161 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 169255
  total_bytes: 169255
}
local_info {
}

2022-03-28 12:07:12,395 INFO    MainThread:12299 [wandb_run.py:_footer_history_summary_info():2865] rendering history
2022-03-28 12:07:12,398 INFO    MainThread:12299 [wandb_run.py:_footer_history_summary_info():2894] rendering summary
2022-03-28 12:07:12,400 INFO    MainThread:12299 [wandb_run.py:_footer_sync_info():2822] logging synced files
