Epoch [1/45] Training loss: 1.2165	 Validation loss: 1.1710
--------------------------------------------------
Epoch [2/45] Training loss: 1.2043	 Validation loss: 1.1689
--------------------------------------------------
Epoch [3/45] Training loss: 1.2058	 Validation loss: 1.1683
--------------------------------------------------
Epoch [4/45] Training loss: 1.1961	 Validation loss: 1.1680
--------------------------------------------------
Epoch [5/45] Training loss: 1.2006	 Validation loss: 1.1674
--------------------------------------------------
Epoch [6/45] Training loss: 1.2001	 Validation loss: 1.1686
--------------------------------------------------
Epoch [7/45] Training loss: 1.1765	 Validation loss: 1.1703
--------------------------------------------------
Epoch [8/45] Training loss: 1.1814	 Validation loss: 1.1693
--------------------------------------------------
Epoch [9/45] Training loss: 1.1743	 Validation loss: 1.1681
--------------------------------------------------
Epoch [10/45] Training loss: 1.1679	 Validation loss: 1.1670
--------------------------------------------------
Epoch [11/45] Training loss: 1.1545	 Validation loss: 1.1654
--------------------------------------------------
Epoch [12/45] Training loss: 1.1508	 Validation loss: 1.1647
--------------------------------------------------
Epoch [13/45] Training loss: 1.1499	 Validation loss: 1.1634
--------------------------------------------------
Epoch [14/45] Training loss: 1.1220	 Validation loss: 1.1630
--------------------------------------------------
Epoch [15/45] Training loss: 1.1203	 Validation loss: 1.1631
--------------------------------------------------
Epoch [16/45] Training loss: 1.1209	 Validation loss: 1.1644
--------------------------------------------------
Epoch [17/45] Training loss: 1.0997	 Validation loss: 1.1655
--------------------------------------------------
Epoch [18/45] Training loss: 1.1104	 Validation loss: 1.1651
--------------------------------------------------
Epoch [19/45] Training loss: 1.0925	 Validation loss: 1.1665
--------------------------------------------------
Epoch [20/45] Training loss: 1.0992	 Validation loss: 1.1676
--------------------------------------------------
Epoch [21/45] Training loss: 1.0928	 Validation loss: 1.1679
--------------------------------------------------
Epoch [22/45] Training loss: 1.0731	 Validation loss: 1.1681
--------------------------------------------------
Epoch [23/45] Training loss: 1.0657	 Validation loss: 1.1692
--------------------------------------------------
Epoch [24/45] Training loss: 1.0620	 Validation loss: 1.1716
--------------------------------------------------
Epoch [25/45] Training loss: 1.0329	 Validation loss: 1.1709
--------------------------------------------------
Epoch [26/45] Training loss: 1.0478	 Validation loss: 1.1717
--------------------------------------------------
Process wandb_internal:
Traceback (most recent call last):
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/wandb/sdk/internal/internal.py", line 162, in wandb_internal
    thread.join()
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/multiprocessing/process.py", line 333, in _bootstrap
    threading._shutdown()
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
KeyboardInterrupt
Exception in thread ChkStopThr:
Traceback (most recent call last):
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 167, in check_status
    status_response = self._interface.communicate_stop_status()
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 114, in communicate_stop_status
    resp = self._communicate_stop_status(status)
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 387, in _communicate_stop_status
    resp = self._communicate(req, local=True)
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 222, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 227, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Exception in thread NetStatThr:
Traceback (most recent call last):
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 149, in check_network_status
    status_response = self._interface.communicate_network_status()
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 125, in communicate_network_status
    resp = self._communicate_network_status(status)
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 397, in _communicate_network_status
    resp = self._communicate(req, local=True)
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 222, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 227, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Error in callback <function _WandbInit._resume_backend at 0x7f83b2c09550> (for pre_run_cell):
Error in callback <function _WandbInit._pause_backend at 0x7f83b2c093a0> (for post_run_cell):
Process wandb_internal:
Traceback (most recent call last):
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/wandb/sdk/internal/internal.py", line 162, in wandb_internal
    thread.join()
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/multiprocessing/process.py", line 333, in _bootstrap
    threading._shutdown()
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
KeyboardInterrupt
Error in callback <function _WandbInit._resume_backend at 0x7f83b2c09550> (for pre_run_cell):
Error in callback <function _WandbInit._pause_backend at 0x7f83b2c093a0> (for post_run_cell):
Error in callback <function _WandbInit._resume_backend at 0x7f83b2c09550> (for pre_run_cell):
Error in callback <function _WandbInit._pause_backend at 0x7f83b2c093a0> (for post_run_cell):