
[32m[I 2022-03-22 11:59:53,954][39m A new study created in memory with name: no-name-03af46ab-f9eb-4d94-b7d1-5b9115c2cebb
Params: {'learning_rate': 0.00013227942034972528, 'num_hidden_units_per_layer': 64, 'weight_decay': 0.002708546732349255, 'kernel_size': 7, 'num_epochs': 20, 'drop_out': 0.18280269730861157, 'batch_size': 60, 'reduced_seq_length': 90, 'num_levels': 4, 'stride': 1}
The number of rows with infinite numbers that will be replaced with zero is: 0
The number of rows with NA numbers that will be replaced with zero is: 0
[33m[W 2022-03-22 12:00:49,450][39m Trial 0 failed because of the following error: AttributeError("'OptimizationTCN' object has no attribute 'criterion'")
Traceback (most recent call last):
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/optuna/study/_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File "/var/folders/16/mg5_s98x3yd90kq7mmfmk3pr0000gn/T/ipykernel_88427/1202499574.py", line 77, in objective_tcn_model_samp_en
    loss = opt_tcn.train(trial, custom_train_loader_samp_en, custom_val_loader_samp_en, config,
  File "/var/folders/16/mg5_s98x3yd90kq7mmfmk3pr0000gn/T/ipykernel_88427/4271848861.py", line 73, in train
    wandb.watch(self.model, self.criterion, log='all', log_freq=1)
AttributeError: 'OptimizationTCN' object has no attribute 'criterion'
The number of rows with infinite numbers that will be replaced with zero is: 0
The number of rows with NA numbers that will be replaced with zero is: 0