2022-03-28 13:22:19,493 INFO    MainThread:12299 [wandb_setup.py:_flush():75] Loading settings from /Users/AFischer/.config/wandb/settings
2022-03-28 13:22:19,494 INFO    MainThread:12299 [wandb_setup.py:_flush():75] Loading settings from /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/settings
2022-03-28 13:22:19,494 INFO    MainThread:12299 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-28 13:22:19,494 INFO    MainThread:12299 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-28 13:22:19,494 INFO    MainThread:12299 [wandb_init.py:_log_setup():405] Logging user logs to /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/run-20220328_132219-g5hqc59t/logs/debug.log
2022-03-28 13:22:19,494 INFO    MainThread:12299 [wandb_init.py:_log_setup():406] Logging internal logs to /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/run-20220328_132219-g5hqc59t/logs/debug-internal.log
2022-03-28 13:22:19,494 INFO    MainThread:12299 [wandb_init.py:_jupyter_setup():355] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f83b4112ee0>
2022-03-28 13:22:19,494 INFO    MainThread:12299 [wandb_init.py:init():439] calling init triggers
2022-03-28 13:22:19,494 INFO    MainThread:12299 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {}
2022-03-28 13:22:19,494 INFO    MainThread:12299 [wandb_init.py:init():458] re-initializing run, found existing run on stack: 3ragan0i
2022-03-28 13:22:19,499 INFO    MainThread:12299 [wandb_run.py:finish():1539] finishing run afischer/tcn_samp_en-project/3ragan0i
2022-03-28 13:22:19,499 INFO    MainThread:12299 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 0
2022-03-28 13:22:19,503 INFO    MainThread:12299 [wandb_run.py:_restore():1674] restore
2022-03-28 13:22:20,035 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 824
  total_bytes: 824
}

2022-03-28 13:22:20,280 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 824
  total_bytes: 824
}

2022-03-28 13:22:20,421 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 824
  total_bytes: 164605
}

2022-03-28 13:22:20,530 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 824
  total_bytes: 170501
}

2022-03-28 13:22:20,637 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 824
  total_bytes: 170501
}

2022-03-28 13:22:20,745 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 170501
  total_bytes: 170501
}

2022-03-28 13:22:20,855 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 170501
  total_bytes: 170501
}

2022-03-28 13:22:20,983 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 170501
  total_bytes: 170501
}

2022-03-28 13:22:21,093 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 170501
  total_bytes: 170501
}

2022-03-28 13:22:21,205 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 170501
  total_bytes: 170501
}

2022-03-28 13:22:21,312 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 170501
  total_bytes: 170501
}

2022-03-28 13:22:21,419 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 170501
  total_bytes: 170501
}

2022-03-28 13:22:21,533 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 170501
  total_bytes: 170501
}

2022-03-28 13:22:22,615 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 170501
  total_bytes: 170501
}

2022-03-28 13:22:23,242 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 170501
  total_bytes: 170501
}
local_info {
}

2022-03-28 13:22:24,464 INFO    MainThread:12299 [wandb_run.py:_footer_history_summary_info():2865] rendering history
2022-03-28 13:22:24,467 INFO    MainThread:12299 [wandb_run.py:_footer_history_summary_info():2894] rendering summary
2022-03-28 13:22:24,475 INFO    MainThread:12299 [wandb_run.py:_footer_sync_info():2822] logging synced files
2022-03-28 13:22:24,478 INFO    MainThread:12299 [wandb_init.py:init():492] starting backend
2022-03-28 13:22:24,478 INFO    MainThread:12299 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2022-03-28 13:22:24,484 INFO    MainThread:12299 [backend.py:ensure_launched():219] starting backend process...
2022-03-28 13:22:24,510 INFO    MainThread:12299 [backend.py:ensure_launched():224] started backend process with pid: 16643
2022-03-28 13:22:24,512 INFO    MainThread:12299 [wandb_init.py:init():501] backend started and connected
2022-03-28 13:22:24,534 INFO    MainThread:12299 [wandb_run.py:_label_probe_notebook():947] probe notebook
2022-03-28 13:22:24,534 INFO    MainThread:12299 [wandb_run.py:_label_probe_notebook():957] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-03-28 13:22:24,534 INFO    MainThread:12299 [wandb_init.py:init():565] updated telemetry
2022-03-28 13:22:24,586 INFO    MainThread:12299 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-03-28 13:22:25,816 INFO    MainThread:12299 [wandb_run.py:_on_init():1759] communicating current version
2022-03-28 13:22:26,163 INFO    MainThread:12299 [wandb_run.py:_on_init():1763] got version response 
2022-03-28 13:22:26,163 INFO    MainThread:12299 [wandb_init.py:init():625] starting run threads in backend
2022-03-28 13:22:28,498 INFO    MainThread:12299 [wandb_run.py:_console_start():1733] atexit reg
2022-03-28 13:22:28,498 INFO    MainThread:12299 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.WRAP
2022-03-28 13:22:28,498 INFO    MainThread:12299 [wandb_run.py:_redirect():1643] Wrapping output streams.
2022-03-28 13:22:28,499 INFO    MainThread:12299 [wandb_run.py:_redirect():1667] Redirects installed.
2022-03-28 13:22:28,499 INFO    MainThread:12299 [wandb_init.py:init():664] run started, returning control to user process
2022-03-28 13:22:28,499 INFO    MainThread:12299 [wandb_watch.py:watch():47] Watching
2022-03-28 13:27:09,417 INFO    MainThread:12299 [wandb_init.py:_pause_backend():318] pausing backend
2022-03-28 13:27:09,418 INFO    MainThread:12299 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-28 13:27:12,286 INFO    MainThread:12299 [wandb_init.py:_resume_backend():327] resuming backend
2022-03-28 13:27:12,295 INFO    MainThread:12299 [wandb_init.py:_pause_backend():318] pausing backend
2022-03-28 13:27:12,295 INFO    MainThread:12299 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-28 13:29:38,709 INFO    MainThread:12299 [wandb_init.py:_resume_backend():327] resuming backend
2022-03-28 13:29:38,742 INFO    MainThread:12299 [wandb_init.py:_pause_backend():318] pausing backend
2022-03-28 13:29:38,743 INFO    MainThread:12299 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-28 13:29:56,122 INFO    MainThread:12299 [wandb_init.py:_resume_backend():327] resuming backend
2022-03-28 13:29:56,141 INFO    MainThread:12299 [wandb_init.py:_pause_backend():318] pausing backend
2022-03-28 13:29:56,141 INFO    MainThread:12299 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-28 13:30:22,433 INFO    MainThread:12299 [wandb_init.py:_resume_backend():327] resuming backend
2022-03-28 13:30:22,454 INFO    MainThread:12299 [wandb_init.py:_pause_backend():318] pausing backend
2022-03-28 13:30:22,454 INFO    MainThread:12299 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-28 13:30:35,576 INFO    MainThread:12299 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 0
2022-03-28 13:30:35,588 INFO    MainThread:12299 [wandb_run.py:_restore():1674] restore
