2022-03-25 13:52:24,983 INFO    MainThread:8658 [wandb_setup.py:_flush():75] Loading settings from /Users/AFischer/.config/wandb/settings
2022-03-25 13:52:24,983 INFO    MainThread:8658 [wandb_setup.py:_flush():75] Loading settings from /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/settings
2022-03-25 13:52:24,983 INFO    MainThread:8658 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-25 13:52:24,983 INFO    MainThread:8658 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-25 13:52:24,983 INFO    MainThread:8658 [wandb_init.py:_log_setup():405] Logging user logs to /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/run-20220325_135224-3kctuxu7/logs/debug.log
2022-03-25 13:52:24,983 INFO    MainThread:8658 [wandb_init.py:_log_setup():406] Logging internal logs to /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/run-20220325_135224-3kctuxu7/logs/debug-internal.log
2022-03-25 13:52:24,983 INFO    MainThread:8658 [wandb_init.py:_jupyter_setup():355] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7faf02a89ee0>
2022-03-25 13:52:24,983 INFO    MainThread:8658 [wandb_init.py:init():439] calling init triggers
2022-03-25 13:52:24,983 INFO    MainThread:8658 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {}
2022-03-25 13:52:24,983 INFO    MainThread:8658 [wandb_init.py:init():458] re-initializing run, found existing run on stack: 33orc8a3
2022-03-25 13:52:24,985 INFO    MainThread:8658 [wandb_run.py:finish():1539] finishing run afischer/tcn_samp_en-project/33orc8a3
2022-03-25 13:52:24,985 INFO    MainThread:8658 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 0
2022-03-25 13:52:24,987 INFO    MainThread:8658 [wandb_run.py:_restore():1674] restore
2022-03-25 13:52:25,107 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 825
}

2022-03-25 13:52:25,242 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 825
}

2022-03-25 13:52:25,455 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 825
}

2022-03-25 13:52:25,982 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 164866
}

2022-03-25 13:52:26,091 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 164866
}

2022-03-25 13:52:26,199 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 164866
}

2022-03-25 13:52:26,301 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 164866
  total_bytes: 164866
}

2022-03-25 13:52:26,413 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 164866
  total_bytes: 164866
}

2022-03-25 13:52:26,518 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 164866
  total_bytes: 164866
}

2022-03-25 13:52:26,627 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 164866
  total_bytes: 164866
}

2022-03-25 13:52:26,733 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 164866
  total_bytes: 164866
}

2022-03-25 13:52:26,844 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 164866
  total_bytes: 164866
}

2022-03-25 13:52:26,952 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 164866
  total_bytes: 164866
}

2022-03-25 13:52:27,060 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 164866
  total_bytes: 164866
}

2022-03-25 13:52:28,133 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 164866
  total_bytes: 164866
}

2022-03-25 13:52:28,654 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 164866
  total_bytes: 164866
}
local_info {
}

2022-03-25 13:52:29,839 INFO    MainThread:8658 [wandb_run.py:_footer_history_summary_info():2865] rendering history
2022-03-25 13:52:29,842 INFO    MainThread:8658 [wandb_run.py:_footer_history_summary_info():2894] rendering summary
2022-03-25 13:52:29,845 INFO    MainThread:8658 [wandb_run.py:_footer_sync_info():2822] logging synced files
2022-03-25 13:52:29,847 INFO    MainThread:8658 [wandb_init.py:init():492] starting backend
2022-03-25 13:52:29,847 INFO    MainThread:8658 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2022-03-25 13:52:29,850 INFO    MainThread:8658 [backend.py:ensure_launched():219] starting backend process...
2022-03-25 13:52:29,874 INFO    MainThread:8658 [backend.py:ensure_launched():224] started backend process with pid: 9488
2022-03-25 13:52:29,876 INFO    MainThread:8658 [wandb_init.py:init():501] backend started and connected
2022-03-25 13:52:29,901 INFO    MainThread:8658 [wandb_run.py:_label_probe_notebook():947] probe notebook
2022-03-25 13:52:29,901 INFO    MainThread:8658 [wandb_run.py:_label_probe_notebook():957] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-03-25 13:52:29,901 INFO    MainThread:8658 [wandb_init.py:init():565] updated telemetry
2022-03-25 13:52:29,940 INFO    MainThread:8658 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-03-25 13:52:30,959 INFO    MainThread:8658 [wandb_run.py:_on_init():1759] communicating current version
2022-03-25 13:52:30,999 INFO    MainThread:8658 [wandb_run.py:_on_init():1763] got version response 
2022-03-25 13:52:30,999 INFO    MainThread:8658 [wandb_init.py:init():625] starting run threads in backend
2022-03-25 13:52:33,250 INFO    MainThread:8658 [wandb_run.py:_console_start():1733] atexit reg
2022-03-25 13:52:33,251 INFO    MainThread:8658 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.WRAP
2022-03-25 13:52:33,251 INFO    MainThread:8658 [wandb_run.py:_redirect():1643] Wrapping output streams.
2022-03-25 13:52:33,251 INFO    MainThread:8658 [wandb_run.py:_redirect():1667] Redirects installed.
2022-03-25 13:52:33,251 INFO    MainThread:8658 [wandb_init.py:init():664] run started, returning control to user process
2022-03-25 13:52:33,252 INFO    MainThread:8658 [wandb_watch.py:watch():47] Watching
2022-03-25 13:53:23,594 INFO    MainThread:8658 [wandb_config.py:__setitem__():153] config set batch_size = 30 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7faf09314bb0>>
2022-03-25 13:53:23,594 INFO    MainThread:8658 [wandb_run.py:_config_callback():992] config_cb batch_size 30 None
2022-03-25 13:53:23,594 INFO    MainThread:8658 [wandb_config.py:__setitem__():153] config set epochs = 30 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7faf09314bb0>>
2022-03-25 13:53:23,594 INFO    MainThread:8658 [wandb_run.py:_config_callback():992] config_cb epochs 30 None
2022-03-25 13:53:23,595 INFO    MainThread:8658 [wandb_config.py:__setitem__():153] config set lr = 0.00020410630917833838 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7faf09314bb0>>
2022-03-25 13:53:23,595 INFO    MainThread:8658 [wandb_run.py:_config_callback():992] config_cb lr 0.00020410630917833838 None
2022-03-25 13:53:23,595 INFO    MainThread:8658 [wandb_config.py:__setitem__():153] config set no_cuda = False - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7faf09314bb0>>
2022-03-25 13:53:23,595 INFO    MainThread:8658 [wandb_run.py:_config_callback():992] config_cb no_cuda False None
2022-03-25 13:53:23,595 INFO    MainThread:8658 [wandb_config.py:__setitem__():153] config set seed = 42 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7faf09314bb0>>
2022-03-25 13:53:23,595 INFO    MainThread:8658 [wandb_run.py:_config_callback():992] config_cb seed 42 None
2022-03-25 13:53:43,105 INFO    MainThread:8658 [wandb_setup.py:_flush():75] Loading settings from /Users/AFischer/.config/wandb/settings
2022-03-25 13:53:43,105 INFO    MainThread:8658 [wandb_setup.py:_flush():75] Loading settings from /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/settings
2022-03-25 13:53:43,105 INFO    MainThread:8658 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-25 13:53:43,105 INFO    MainThread:8658 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-25 13:53:43,105 INFO    MainThread:8658 [wandb_init.py:_log_setup():405] Logging user logs to /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/run-20220325_135343-1ubom50q/logs/debug.log
2022-03-25 13:53:43,105 INFO    MainThread:8658 [wandb_init.py:_log_setup():406] Logging internal logs to /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/run-20220325_135343-1ubom50q/logs/debug-internal.log
2022-03-25 13:53:43,105 INFO    MainThread:8658 [wandb_init.py:init():439] calling init triggers
2022-03-25 13:53:43,105 INFO    MainThread:8658 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {}
2022-03-25 13:53:43,105 INFO    MainThread:8658 [wandb_init.py:init():458] re-initializing run, found existing run on stack: 3kctuxu7
2022-03-25 13:53:43,107 INFO    MainThread:8658 [wandb_run.py:finish():1539] finishing run afischer/tcn_samp_en-project/3kctuxu7
2022-03-25 13:53:43,107 INFO    MainThread:8658 [jupyter.py:save_history():429] not saving jupyter history
2022-03-25 13:53:43,107 INFO    MainThread:8658 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-25 13:53:43,108 INFO    MainThread:8658 [wandb_init.py:_jupyter_teardown():337] cleaning up jupyter logic
2022-03-25 13:53:43,108 INFO    MainThread:8658 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 0
2022-03-25 13:53:43,109 INFO    MainThread:8658 [wandb_run.py:_restore():1674] restore
2022-03-25 13:53:43,601 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 825
}

2022-03-25 13:53:43,714 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 825
}

2022-03-25 13:53:43,923 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 825
}

2022-03-25 13:53:44,352 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 121472
}

2022-03-25 13:53:44,462 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 121472
}

2022-03-25 13:53:44,568 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 118551
  total_bytes: 121472
}

2022-03-25 13:53:44,677 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 118551
  total_bytes: 121472
}

2022-03-25 13:53:44,786 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 121472
  total_bytes: 121472
}

2022-03-25 13:53:44,897 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 121472
  total_bytes: 121472
}

2022-03-25 13:53:45,010 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 121472
  total_bytes: 121472
}

2022-03-25 13:53:45,119 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 121472
  total_bytes: 121472
}

2022-03-25 13:53:45,228 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 121472
  total_bytes: 121472
}

2022-03-25 13:53:45,332 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 121472
  total_bytes: 121472
}

2022-03-25 13:53:46,316 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 121472
  total_bytes: 121472
}

2022-03-25 13:53:46,755 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 121472
  total_bytes: 121472
}
local_info {
}

2022-03-25 13:53:47,920 INFO    MainThread:8658 [wandb_run.py:_footer_history_summary_info():2865] rendering history
2022-03-25 13:53:47,922 INFO    MainThread:8658 [wandb_run.py:_footer_history_summary_info():2894] rendering summary
2022-03-25 13:53:47,925 INFO    MainThread:8658 [wandb_run.py:_footer_sync_info():2822] logging synced files
