2022-03-22 13:31:24,944 INFO    MainThread:88427 [wandb_setup.py:_flush():75] Loading settings from /Users/AFischer/.config/wandb/settings
2022-03-22 13:31:24,945 INFO    MainThread:88427 [wandb_setup.py:_flush():75] Loading settings from /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/settings
2022-03-22 13:31:24,945 INFO    MainThread:88427 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-22 13:31:24,945 INFO    MainThread:88427 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-22 13:31:24,945 INFO    MainThread:88427 [wandb_init.py:_log_setup():405] Logging user logs to /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/run-20220322_133124-3ii8ryyd/logs/debug.log
2022-03-22 13:31:24,945 INFO    MainThread:88427 [wandb_init.py:_log_setup():406] Logging internal logs to /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/run-20220322_133124-3ii8ryyd/logs/debug-internal.log
2022-03-22 13:31:24,945 INFO    MainThread:88427 [wandb_init.py:_jupyter_setup():355] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fb3b088a2b0>
2022-03-22 13:31:24,946 INFO    MainThread:88427 [wandb_init.py:init():439] calling init triggers
2022-03-22 13:31:24,946 INFO    MainThread:88427 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {}
2022-03-22 13:31:24,946 INFO    MainThread:88427 [wandb_init.py:init():492] starting backend
2022-03-22 13:31:24,946 INFO    MainThread:88427 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2022-03-22 13:31:24,951 INFO    MainThread:88427 [backend.py:ensure_launched():219] starting backend process...
2022-03-22 13:31:24,970 INFO    MainThread:88427 [backend.py:ensure_launched():224] started backend process with pid: 91771
2022-03-22 13:31:24,972 INFO    MainThread:88427 [wandb_init.py:init():501] backend started and connected
2022-03-22 13:31:25,005 INFO    MainThread:88427 [wandb_run.py:_label_probe_notebook():947] probe notebook
2022-03-22 13:31:25,005 INFO    MainThread:88427 [wandb_run.py:_label_probe_notebook():957] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-03-22 13:31:25,005 INFO    MainThread:88427 [wandb_init.py:init():565] updated telemetry
2022-03-22 13:31:25,082 INFO    MainThread:88427 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-03-22 13:31:26,030 INFO    MainThread:88427 [wandb_run.py:_on_init():1759] communicating current version
2022-03-22 13:31:26,069 INFO    MainThread:88427 [wandb_run.py:_on_init():1763] got version response 
2022-03-22 13:31:26,069 INFO    MainThread:88427 [wandb_init.py:init():625] starting run threads in backend
2022-03-22 13:31:28,399 INFO    MainThread:88427 [wandb_run.py:_console_start():1733] atexit reg
2022-03-22 13:31:28,400 INFO    MainThread:88427 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.WRAP
2022-03-22 13:31:28,400 INFO    MainThread:88427 [wandb_run.py:_redirect():1643] Wrapping output streams.
2022-03-22 13:31:28,401 INFO    MainThread:88427 [wandb_run.py:_redirect():1667] Redirects installed.
2022-03-22 13:31:28,401 INFO    MainThread:88427 [wandb_init.py:init():664] run started, returning control to user process
2022-03-22 13:31:28,404 INFO    MainThread:88427 [wandb_init.py:_pause_backend():318] pausing backend
2022-03-22 13:31:28,405 INFO    MainThread:88427 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-22 13:32:38,680 INFO    MainThread:88427 [wandb_init.py:_resume_backend():327] resuming backend
2022-03-22 13:32:38,686 INFO    MainThread:88427 [wandb_init.py:_pause_backend():318] pausing backend
2022-03-22 13:32:38,686 INFO    MainThread:88427 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-22 13:32:39,798 INFO    MainThread:88427 [wandb_init.py:_resume_backend():327] resuming backend
2022-03-22 13:32:39,802 INFO    MainThread:88427 [wandb_init.py:_pause_backend():318] pausing backend
2022-03-22 13:32:39,803 INFO    MainThread:88427 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-22 13:32:40,244 INFO    MainThread:88427 [wandb_init.py:_resume_backend():327] resuming backend
2022-03-22 13:32:40,250 INFO    MainThread:88427 [wandb_init.py:_pause_backend():318] pausing backend
2022-03-22 13:32:40,251 INFO    MainThread:88427 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-22 13:32:41,077 INFO    MainThread:88427 [wandb_init.py:_resume_backend():327] resuming backend
2022-03-22 13:32:41,169 INFO    MainThread:88427 [wandb_init.py:_pause_backend():318] pausing backend
2022-03-22 13:32:41,169 INFO    MainThread:88427 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-22 13:33:08,132 INFO    MainThread:88427 [wandb_init.py:_resume_backend():327] resuming backend
2022-03-22 13:33:08,136 INFO    MainThread:88427 [wandb_init.py:_pause_backend():318] pausing backend
2022-03-22 13:33:08,136 INFO    MainThread:88427 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-22 13:33:09,127 INFO    MainThread:88427 [wandb_init.py:_resume_backend():327] resuming backend
2022-03-22 13:33:09,131 INFO    MainThread:88427 [wandb_init.py:_pause_backend():318] pausing backend
2022-03-22 13:33:09,131 INFO    MainThread:88427 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-22 13:33:09,590 INFO    MainThread:88427 [wandb_init.py:_resume_backend():327] resuming backend
2022-03-22 13:33:09,594 INFO    MainThread:88427 [wandb_init.py:_pause_backend():318] pausing backend
2022-03-22 13:33:09,594 INFO    MainThread:88427 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-22 13:33:10,000 INFO    MainThread:88427 [wandb_init.py:_resume_backend():327] resuming backend
2022-03-22 13:33:10,030 INFO    MainThread:88427 [wandb_config.py:__setitem__():153] config set batch_size = 10 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fb2a81322b0>>
2022-03-22 13:33:10,030 INFO    MainThread:88427 [wandb_run.py:_config_callback():992] config_cb batch_size 10 None
2022-03-22 13:33:10,031 INFO    MainThread:88427 [wandb_config.py:__setitem__():153] config set epochs = 25 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fb2a81322b0>>
2022-03-22 13:33:10,031 INFO    MainThread:88427 [wandb_run.py:_config_callback():992] config_cb epochs 25 None
2022-03-22 13:33:10,031 INFO    MainThread:88427 [wandb_config.py:__setitem__():153] config set lr = 7.09359897484749e-05 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fb2a81322b0>>
2022-03-22 13:33:10,031 INFO    MainThread:88427 [wandb_run.py:_config_callback():992] config_cb lr 7.09359897484749e-05 None
2022-03-22 13:33:10,031 INFO    MainThread:88427 [wandb_config.py:__setitem__():153] config set no_cuda = False - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fb2a81322b0>>
2022-03-22 13:33:10,031 INFO    MainThread:88427 [wandb_run.py:_config_callback():992] config_cb no_cuda False None
2022-03-22 13:33:10,031 INFO    MainThread:88427 [wandb_config.py:__setitem__():153] config set seed = 42 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fb2a81322b0>>
2022-03-22 13:33:10,031 INFO    MainThread:88427 [wandb_run.py:_config_callback():992] config_cb seed 42 None
2022-03-22 13:38:42,779 INFO    MainThread:88427 [wandb_watch.py:watch():47] Watching
2022-03-22 13:39:03,541 INFO    MainThread:88427 [wandb_config.py:__setitem__():153] config set batch_size = 10 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fb2a81322b0>>
2022-03-22 13:39:03,542 INFO    MainThread:88427 [wandb_run.py:_config_callback():992] config_cb batch_size 10 None
2022-03-22 13:39:03,542 INFO    MainThread:88427 [wandb_config.py:__setitem__():153] config set epochs = 25 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fb2a81322b0>>
2022-03-22 13:39:03,542 INFO    MainThread:88427 [wandb_run.py:_config_callback():992] config_cb epochs 25 None
2022-03-22 13:39:03,542 INFO    MainThread:88427 [wandb_config.py:__setitem__():153] config set lr = 7.09359897484749e-05 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fb2a81322b0>>
2022-03-22 13:39:03,543 INFO    MainThread:88427 [wandb_run.py:_config_callback():992] config_cb lr 7.09359897484749e-05 None
2022-03-22 13:39:03,543 INFO    MainThread:88427 [wandb_config.py:__setitem__():153] config set no_cuda = False - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fb2a81322b0>>
2022-03-22 13:39:03,543 INFO    MainThread:88427 [wandb_run.py:_config_callback():992] config_cb no_cuda False None
2022-03-22 13:39:03,543 INFO    MainThread:88427 [wandb_config.py:__setitem__():153] config set seed = 42 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fb2a81322b0>>
2022-03-22 13:39:03,543 INFO    MainThread:88427 [wandb_run.py:_config_callback():992] config_cb seed 42 None
2022-03-22 13:44:34,461 INFO    MainThread:88427 [wandb_watch.py:watch():47] Watching
2022-03-22 13:44:47,502 INFO    MainThread:88427 [wandb_init.py:_pause_backend():318] pausing backend
2022-03-22 13:44:47,502 INFO    MainThread:88427 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-22 13:46:38,876 INFO    MainThread:88427 [wandb_init.py:_resume_backend():327] resuming backend
2022-03-22 13:46:38,905 INFO    MainThread:88427 [wandb_init.py:_pause_backend():318] pausing backend
2022-03-22 13:46:38,905 INFO    MainThread:88427 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-22 13:46:53,709 INFO    MainThread:88427 [wandb_init.py:_resume_backend():327] resuming backend
2022-03-22 13:46:53,745 INFO    MainThread:88427 [wandb_setup.py:_flush():75] Loading settings from /Users/AFischer/.config/wandb/settings
2022-03-22 13:46:53,746 INFO    MainThread:88427 [wandb_setup.py:_flush():75] Loading settings from /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/settings
2022-03-22 13:46:53,746 INFO    MainThread:88427 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-22 13:46:53,746 INFO    MainThread:88427 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-22 13:46:53,746 INFO    MainThread:88427 [wandb_init.py:_log_setup():405] Logging user logs to /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/run-20220322_134653-uob5y5xu/logs/debug.log
2022-03-22 13:46:53,746 INFO    MainThread:88427 [wandb_init.py:_log_setup():406] Logging internal logs to /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/run-20220322_134653-uob5y5xu/logs/debug-internal.log
2022-03-22 13:46:53,746 INFO    MainThread:88427 [wandb_init.py:init():439] calling init triggers
2022-03-22 13:46:53,746 INFO    MainThread:88427 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {}
2022-03-22 13:46:53,746 INFO    MainThread:88427 [wandb_init.py:init():458] re-initializing run, found existing run on stack: 3ii8ryyd
2022-03-22 13:46:53,767 ERROR   MainThread:88427 [wandb_init.py:init():981] error
Traceback (most recent call last):
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 954, in init
    run = wi.init()
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 471, in init
    self._wl._global_run_stack[-1].finish()
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1538, in finish
    tel.feature.finish = True
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/wandb/sdk/lib/telemetry.py", line 43, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 470, in _telemetry_callback
    self._telemetry_flush()
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 481, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 73, in _publish_telemetry
    self._publish(rec)
  File "/Users/AFischer/opt/anaconda3/envs/ai_medicine/lib/python3.8/site-packages/wandb/sdk/interface/interface_queue.py", line 49, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2022-03-22 13:46:55,844 INFO    MainThread:88427 [wandb_init.py:_pause_backend():318] pausing backend
2022-03-22 13:46:55,845 INFO    MainThread:88427 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-22 13:47:47,520 INFO    MainThread:88427 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 0
2022-03-22 13:47:47,584 INFO    MainThread:88427 [wandb_run.py:_restore():1674] restore
