2022-03-28 10:59:17,524 INFO    MainThread:12299 [wandb_setup.py:_flush():75] Loading settings from /Users/AFischer/.config/wandb/settings
2022-03-28 10:59:17,525 INFO    MainThread:12299 [wandb_setup.py:_flush():75] Loading settings from /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/settings
2022-03-28 10:59:17,525 INFO    MainThread:12299 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-28 10:59:17,525 INFO    MainThread:12299 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-28 10:59:17,525 INFO    MainThread:12299 [wandb_init.py:_log_setup():405] Logging user logs to /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/run-20220328_105917-142qtgdn/logs/debug.log
2022-03-28 10:59:17,525 INFO    MainThread:12299 [wandb_init.py:_log_setup():406] Logging internal logs to /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/run-20220328_105917-142qtgdn/logs/debug-internal.log
2022-03-28 10:59:17,525 INFO    MainThread:12299 [wandb_init.py:init():439] calling init triggers
2022-03-28 10:59:17,525 INFO    MainThread:12299 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {}
2022-03-28 10:59:17,525 INFO    MainThread:12299 [wandb_init.py:init():458] re-initializing run, found existing run on stack: 3ngadcxz
2022-03-28 10:59:17,527 INFO    MainThread:12299 [wandb_run.py:finish():1539] finishing run afischer/tcn_samp_en-project/3ngadcxz
2022-03-28 10:59:17,527 INFO    MainThread:12299 [jupyter.py:save_history():429] not saving jupyter history
2022-03-28 10:59:17,528 INFO    MainThread:12299 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-28 10:59:17,528 INFO    MainThread:12299 [wandb_init.py:_jupyter_teardown():337] cleaning up jupyter logic
2022-03-28 10:59:17,528 INFO    MainThread:12299 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 0
2022-03-28 10:59:17,528 INFO    MainThread:12299 [wandb_run.py:_restore():1674] restore
2022-03-28 10:59:18,080 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 824
  total_bytes: 824
}

2022-03-28 10:59:18,401 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 824
  total_bytes: 824
}

2022-03-28 10:59:19,222 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 824
  total_bytes: 143508
}

2022-03-28 10:59:19,331 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 824
  total_bytes: 143508
}

2022-03-28 10:59:19,436 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 824
  total_bytes: 143508
}

2022-03-28 10:59:19,545 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 137612
  total_bytes: 143508
}

2022-03-28 10:59:19,652 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 137612
  total_bytes: 143508
}

2022-03-28 10:59:19,769 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 143508
  total_bytes: 143508
}

2022-03-28 10:59:19,877 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 143508
  total_bytes: 143508
}

2022-03-28 10:59:19,980 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 143508
  total_bytes: 143508
}

2022-03-28 10:59:20,089 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 143508
  total_bytes: 143508
}

2022-03-28 10:59:20,198 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 143508
  total_bytes: 143508
}

2022-03-28 10:59:21,329 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 143508
  total_bytes: 143508
}

2022-03-28 10:59:22,074 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 143508
  total_bytes: 143508
}
local_info {
}

2022-03-28 10:59:23,293 INFO    MainThread:12299 [wandb_run.py:_footer_history_summary_info():2865] rendering history
2022-03-28 10:59:23,295 INFO    MainThread:12299 [wandb_run.py:_footer_history_summary_info():2894] rendering summary
2022-03-28 10:59:23,299 INFO    MainThread:12299 [wandb_run.py:_footer_sync_info():2822] logging synced files
2022-03-28 10:59:23,302 INFO    MainThread:12299 [wandb_init.py:init():492] starting backend
2022-03-28 10:59:23,302 INFO    MainThread:12299 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2022-03-28 10:59:23,305 INFO    MainThread:12299 [backend.py:ensure_launched():219] starting backend process...
2022-03-28 10:59:23,341 INFO    MainThread:12299 [backend.py:ensure_launched():224] started backend process with pid: 14586
2022-03-28 10:59:23,345 INFO    MainThread:12299 [wandb_init.py:init():501] backend started and connected
2022-03-28 10:59:23,373 INFO    MainThread:12299 [wandb_run.py:_label_probe_notebook():947] probe notebook
2022-03-28 10:59:23,373 INFO    MainThread:12299 [wandb_run.py:_label_probe_notebook():957] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-03-28 10:59:23,373 INFO    MainThread:12299 [wandb_init.py:init():565] updated telemetry
2022-03-28 10:59:23,431 INFO    MainThread:12299 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-03-28 10:59:24,688 INFO    MainThread:12299 [wandb_run.py:_on_init():1759] communicating current version
2022-03-28 10:59:24,737 INFO    MainThread:12299 [wandb_run.py:_on_init():1763] got version response 
2022-03-28 10:59:24,737 INFO    MainThread:12299 [wandb_init.py:init():625] starting run threads in backend
2022-03-28 10:59:27,032 INFO    MainThread:12299 [wandb_run.py:_console_start():1733] atexit reg
2022-03-28 10:59:27,033 INFO    MainThread:12299 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.WRAP
2022-03-28 10:59:27,033 INFO    MainThread:12299 [wandb_run.py:_redirect():1643] Wrapping output streams.
2022-03-28 10:59:27,034 INFO    MainThread:12299 [wandb_run.py:_redirect():1667] Redirects installed.
2022-03-28 10:59:27,034 INFO    MainThread:12299 [wandb_init.py:init():664] run started, returning control to user process
2022-03-28 10:59:27,034 INFO    MainThread:12299 [wandb_watch.py:watch():47] Watching
2022-03-28 11:10:15,152 INFO    MainThread:12299 [wandb_config.py:__setitem__():153] config set batch_size = 30 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7f83b6eca700>>
2022-03-28 11:10:15,152 INFO    MainThread:12299 [wandb_run.py:_config_callback():992] config_cb batch_size 30 None
2022-03-28 11:10:15,153 INFO    MainThread:12299 [wandb_config.py:__setitem__():153] config set epochs = 35 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7f83b6eca700>>
2022-03-28 11:10:15,153 INFO    MainThread:12299 [wandb_run.py:_config_callback():992] config_cb epochs 35 None
2022-03-28 11:10:15,153 INFO    MainThread:12299 [wandb_config.py:__setitem__():153] config set lr = 0.00012770770043511842 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7f83b6eca700>>
2022-03-28 11:10:15,153 INFO    MainThread:12299 [wandb_run.py:_config_callback():992] config_cb lr 0.00012770770043511842 None
2022-03-28 11:10:15,153 INFO    MainThread:12299 [wandb_config.py:__setitem__():153] config set no_cuda = False - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7f83b6eca700>>
2022-03-28 11:10:15,153 INFO    MainThread:12299 [wandb_run.py:_config_callback():992] config_cb no_cuda False None
2022-03-28 11:10:15,153 INFO    MainThread:12299 [wandb_config.py:__setitem__():153] config set seed = 42 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7f83b6eca700>>
2022-03-28 11:10:15,153 INFO    MainThread:12299 [wandb_run.py:_config_callback():992] config_cb seed 42 None
2022-03-28 11:10:35,754 INFO    MainThread:12299 [wandb_setup.py:_flush():75] Loading settings from /Users/AFischer/.config/wandb/settings
2022-03-28 11:10:35,754 INFO    MainThread:12299 [wandb_setup.py:_flush():75] Loading settings from /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/settings
2022-03-28 11:10:35,754 INFO    MainThread:12299 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-28 11:10:35,754 INFO    MainThread:12299 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-28 11:10:35,754 INFO    MainThread:12299 [wandb_init.py:_log_setup():405] Logging user logs to /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/run-20220328_111035-27tb6sh7/logs/debug.log
2022-03-28 11:10:35,754 INFO    MainThread:12299 [wandb_init.py:_log_setup():406] Logging internal logs to /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/run-20220328_111035-27tb6sh7/logs/debug-internal.log
2022-03-28 11:10:35,754 INFO    MainThread:12299 [wandb_init.py:_jupyter_setup():355] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f83a21f5040>
2022-03-28 11:10:35,754 INFO    MainThread:12299 [wandb_init.py:init():439] calling init triggers
2022-03-28 11:10:35,755 INFO    MainThread:12299 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {}
2022-03-28 11:10:35,755 INFO    MainThread:12299 [wandb_init.py:init():458] re-initializing run, found existing run on stack: 142qtgdn
2022-03-28 11:10:35,756 INFO    MainThread:12299 [wandb_run.py:finish():1539] finishing run afischer/tcn_samp_en-project/142qtgdn
2022-03-28 11:10:35,757 INFO    MainThread:12299 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 0
2022-03-28 11:10:35,758 INFO    MainThread:12299 [wandb_run.py:_restore():1674] restore
2022-03-28 11:10:36,331 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 824
  total_bytes: 824
}

2022-03-28 11:10:36,566 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 824
  total_bytes: 824
}

2022-03-28 11:10:37,504 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 824
  total_bytes: 121651
}

2022-03-28 11:10:37,614 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 824
  total_bytes: 121651
}

2022-03-28 11:10:37,721 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 824
  total_bytes: 121651
}

2022-03-28 11:10:37,838 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 121651
  total_bytes: 121651
}

2022-03-28 11:10:37,956 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 121651
  total_bytes: 121651
}

2022-03-28 11:10:38,067 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 121651
  total_bytes: 121651
}

2022-03-28 11:10:38,175 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 121651
  total_bytes: 121651
}

2022-03-28 11:10:38,285 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 121651
  total_bytes: 121651
}

2022-03-28 11:10:38,393 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 121651
  total_bytes: 121651
}

2022-03-28 11:10:38,502 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 121651
  total_bytes: 121651
}

2022-03-28 11:10:39,496 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 121651
  total_bytes: 121651
}

2022-03-28 11:10:39,974 INFO    MainThread:12299 [wandb_run.py:_on_finish():1831] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 121651
  total_bytes: 121651
}
local_info {
}

2022-03-28 11:10:41,150 INFO    MainThread:12299 [wandb_run.py:_footer_history_summary_info():2865] rendering history
2022-03-28 11:10:41,152 INFO    MainThread:12299 [wandb_run.py:_footer_history_summary_info():2894] rendering summary
2022-03-28 11:10:41,154 INFO    MainThread:12299 [wandb_run.py:_footer_sync_info():2822] logging synced files
