2022-03-25 13:35:47,972 INFO    MainThread:8658 [wandb_setup.py:_flush():75] Loading settings from /Users/AFischer/.config/wandb/settings
2022-03-25 13:35:47,972 INFO    MainThread:8658 [wandb_setup.py:_flush():75] Loading settings from /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/settings
2022-03-25 13:35:47,972 INFO    MainThread:8658 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-25 13:35:47,972 INFO    MainThread:8658 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-25 13:35:47,973 INFO    MainThread:8658 [wandb_init.py:_log_setup():405] Logging user logs to /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/run-20220325_133547-1f92s2yj/logs/debug.log
2022-03-25 13:35:47,973 INFO    MainThread:8658 [wandb_init.py:_log_setup():406] Logging internal logs to /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/run-20220325_133547-1f92s2yj/logs/debug-internal.log
2022-03-25 13:35:47,973 INFO    MainThread:8658 [wandb_init.py:_jupyter_setup():355] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7faf02e697f0>
2022-03-25 13:35:47,973 INFO    MainThread:8658 [wandb_init.py:init():439] calling init triggers
2022-03-25 13:35:47,974 INFO    MainThread:8658 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {}
2022-03-25 13:35:47,974 INFO    MainThread:8658 [wandb_init.py:init():458] re-initializing run, found existing run on stack: 12q5wr48
2022-03-25 13:35:47,975 INFO    MainThread:8658 [wandb_run.py:finish():1539] finishing run afischer/tcn_samp_en-project/12q5wr48
2022-03-25 13:35:47,975 INFO    MainThread:8658 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 0
2022-03-25 13:35:48,001 INFO    MainThread:8658 [wandb_run.py:_restore():1674] restore
2022-03-25 13:35:48,813 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 825
}

2022-03-25 13:35:48,951 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 825
}

2022-03-25 13:35:49,159 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 825
}

2022-03-25 13:35:49,971 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 825
}

2022-03-25 13:35:50,080 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 144330
}

2022-03-25 13:35:50,203 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 144330
}

2022-03-25 13:35:50,314 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 144330
  total_bytes: 144330
}

2022-03-25 13:35:50,425 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 144330
  total_bytes: 144330
}

2022-03-25 13:35:50,536 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 144330
  total_bytes: 144330
}

2022-03-25 13:35:50,644 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 144330
  total_bytes: 144330
}

2022-03-25 13:35:50,751 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 144330
  total_bytes: 144330
}

2022-03-25 13:35:50,859 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 144330
  total_bytes: 144330
}

2022-03-25 13:35:50,973 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 144330
  total_bytes: 144330
}

2022-03-25 13:35:51,461 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 144330
  total_bytes: 144330
}

2022-03-25 13:35:51,894 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 144330
  total_bytes: 144330
}
local_info {
}

2022-03-25 13:35:53,049 INFO    MainThread:8658 [wandb_run.py:_footer_history_summary_info():2865] rendering history
2022-03-25 13:35:53,052 INFO    MainThread:8658 [wandb_run.py:_footer_history_summary_info():2894] rendering summary
2022-03-25 13:35:53,055 INFO    MainThread:8658 [wandb_run.py:_footer_sync_info():2822] logging synced files
2022-03-25 13:35:53,059 INFO    MainThread:8658 [wandb_init.py:init():492] starting backend
2022-03-25 13:35:53,059 INFO    MainThread:8658 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2022-03-25 13:35:53,063 INFO    MainThread:8658 [backend.py:ensure_launched():219] starting backend process...
2022-03-25 13:35:53,084 INFO    MainThread:8658 [backend.py:ensure_launched():224] started backend process with pid: 9231
2022-03-25 13:35:53,086 INFO    MainThread:8658 [wandb_init.py:init():501] backend started and connected
2022-03-25 13:35:53,107 INFO    MainThread:8658 [wandb_run.py:_label_probe_notebook():947] probe notebook
2022-03-25 13:35:53,107 INFO    MainThread:8658 [wandb_run.py:_label_probe_notebook():957] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-03-25 13:35:53,107 INFO    MainThread:8658 [wandb_init.py:init():565] updated telemetry
2022-03-25 13:35:53,142 INFO    MainThread:8658 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-03-25 13:35:54,129 INFO    MainThread:8658 [wandb_run.py:_on_init():1759] communicating current version
2022-03-25 13:35:54,166 INFO    MainThread:8658 [wandb_run.py:_on_init():1763] got version response 
2022-03-25 13:35:54,167 INFO    MainThread:8658 [wandb_init.py:init():625] starting run threads in backend
2022-03-25 13:35:56,517 INFO    MainThread:8658 [wandb_run.py:_console_start():1733] atexit reg
2022-03-25 13:35:56,518 INFO    MainThread:8658 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.WRAP
2022-03-25 13:35:56,518 INFO    MainThread:8658 [wandb_run.py:_redirect():1643] Wrapping output streams.
2022-03-25 13:35:56,519 INFO    MainThread:8658 [wandb_run.py:_redirect():1667] Redirects installed.
2022-03-25 13:35:56,519 INFO    MainThread:8658 [wandb_init.py:init():664] run started, returning control to user process
2022-03-25 13:35:56,520 INFO    MainThread:8658 [wandb_watch.py:watch():47] Watching
2022-03-25 13:36:05,599 INFO    MainThread:8658 [wandb_config.py:__setitem__():153] config set batch_size = 40 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7faf02a896a0>>
2022-03-25 13:36:05,600 INFO    MainThread:8658 [wandb_run.py:_config_callback():992] config_cb batch_size 40 None
2022-03-25 13:36:05,600 INFO    MainThread:8658 [wandb_config.py:__setitem__():153] config set epochs = 25 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7faf02a896a0>>
2022-03-25 13:36:05,600 INFO    MainThread:8658 [wandb_run.py:_config_callback():992] config_cb epochs 25 None
2022-03-25 13:36:05,600 INFO    MainThread:8658 [wandb_config.py:__setitem__():153] config set lr = 0.00764775995135355 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7faf02a896a0>>
2022-03-25 13:36:05,600 INFO    MainThread:8658 [wandb_run.py:_config_callback():992] config_cb lr 0.00764775995135355 None
2022-03-25 13:36:05,600 INFO    MainThread:8658 [wandb_config.py:__setitem__():153] config set no_cuda = False - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7faf02a896a0>>
2022-03-25 13:36:05,600 INFO    MainThread:8658 [wandb_run.py:_config_callback():992] config_cb no_cuda False None
2022-03-25 13:36:05,600 INFO    MainThread:8658 [wandb_config.py:__setitem__():153] config set seed = 42 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7faf02a896a0>>
2022-03-25 13:36:05,600 INFO    MainThread:8658 [wandb_run.py:_config_callback():992] config_cb seed 42 None
2022-03-25 13:36:21,492 INFO    MainThread:8658 [wandb_setup.py:_flush():75] Loading settings from /Users/AFischer/.config/wandb/settings
2022-03-25 13:36:21,492 INFO    MainThread:8658 [wandb_setup.py:_flush():75] Loading settings from /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/settings
2022-03-25 13:36:21,492 INFO    MainThread:8658 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-25 13:36:21,492 INFO    MainThread:8658 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-25 13:36:21,492 INFO    MainThread:8658 [wandb_init.py:_log_setup():405] Logging user logs to /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/run-20220325_133621-b919kywq/logs/debug.log
2022-03-25 13:36:21,492 INFO    MainThread:8658 [wandb_init.py:_log_setup():406] Logging internal logs to /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/run-20220325_133621-b919kywq/logs/debug-internal.log
2022-03-25 13:36:21,492 INFO    MainThread:8658 [wandb_init.py:init():439] calling init triggers
2022-03-25 13:36:21,493 INFO    MainThread:8658 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {}
2022-03-25 13:36:21,493 INFO    MainThread:8658 [wandb_init.py:init():458] re-initializing run, found existing run on stack: 1f92s2yj
2022-03-25 13:36:21,494 INFO    MainThread:8658 [wandb_run.py:finish():1539] finishing run afischer/tcn_samp_en-project/1f92s2yj
2022-03-25 13:36:21,495 INFO    MainThread:8658 [jupyter.py:save_history():429] not saving jupyter history
2022-03-25 13:36:21,495 INFO    MainThread:8658 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-25 13:36:21,495 INFO    MainThread:8658 [wandb_init.py:_jupyter_teardown():337] cleaning up jupyter logic
2022-03-25 13:36:21,495 INFO    MainThread:8658 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 0
2022-03-25 13:36:21,496 INFO    MainThread:8658 [wandb_run.py:_restore():1674] restore
2022-03-25 13:36:22,274 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 825
}

2022-03-25 13:36:22,495 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 825
}

2022-03-25 13:36:23,268 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 96272
}

2022-03-25 13:36:23,375 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 96272
}

2022-03-25 13:36:23,481 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 96272
}

2022-03-25 13:36:23,588 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 96272
  total_bytes: 96272
}

2022-03-25 13:36:23,697 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 96272
  total_bytes: 96272
}

2022-03-25 13:36:23,801 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 96272
  total_bytes: 96272
}

2022-03-25 13:36:23,912 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 96272
  total_bytes: 96272
}

2022-03-25 13:36:24,022 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 96272
  total_bytes: 96272
}

2022-03-25 13:36:24,130 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 96272
  total_bytes: 96272
}

2022-03-25 13:36:24,239 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 96272
  total_bytes: 96272
}

2022-03-25 13:36:24,345 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 96272
  total_bytes: 96272
}

2022-03-25 13:36:24,863 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 96272
  total_bytes: 96272
}

2022-03-25 13:36:25,380 INFO    MainThread:8658 [wandb_run.py:_on_finish():1831] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 96272
  total_bytes: 96272
}
local_info {
}

2022-03-25 13:36:26,520 INFO    MainThread:8658 [wandb_run.py:_footer_history_summary_info():2865] rendering history
2022-03-25 13:36:26,522 INFO    MainThread:8658 [wandb_run.py:_footer_history_summary_info():2894] rendering summary
2022-03-25 13:36:26,524 INFO    MainThread:8658 [wandb_run.py:_footer_sync_info():2822] logging synced files
