2022-03-22 15:19:43,583 INFO    MainThread:91914 [wandb_setup.py:_flush():75] Loading settings from /Users/AFischer/.config/wandb/settings
2022-03-22 15:19:43,583 INFO    MainThread:91914 [wandb_setup.py:_flush():75] Loading settings from /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/settings
2022-03-22 15:19:43,583 INFO    MainThread:91914 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-22 15:19:43,583 INFO    MainThread:91914 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-22 15:19:43,583 INFO    MainThread:91914 [wandb_init.py:_log_setup():405] Logging user logs to /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/run-20220322_151943-jj9jhchn/logs/debug.log
2022-03-22 15:19:43,583 INFO    MainThread:91914 [wandb_init.py:_log_setup():406] Logging internal logs to /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/run-20220322_151943-jj9jhchn/logs/debug-internal.log
2022-03-22 15:19:43,583 INFO    MainThread:91914 [wandb_init.py:init():439] calling init triggers
2022-03-22 15:19:43,583 INFO    MainThread:91914 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {}
2022-03-22 15:19:43,583 INFO    MainThread:91914 [wandb_init.py:init():458] re-initializing run, found existing run on stack: 2ytdd3gi
2022-03-22 15:19:43,585 INFO    MainThread:91914 [wandb_run.py:finish():1539] finishing run afischer/tcn_samp_en-project/2ytdd3gi
2022-03-22 15:19:43,586 INFO    MainThread:91914 [jupyter.py:save_history():429] not saving jupyter history
2022-03-22 15:19:43,586 INFO    MainThread:91914 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-22 15:19:43,586 INFO    MainThread:91914 [wandb_init.py:_jupyter_teardown():337] cleaning up jupyter logic
2022-03-22 15:19:43,586 INFO    MainThread:91914 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 0
2022-03-22 15:19:43,587 INFO    MainThread:91914 [wandb_run.py:_restore():1674] restore
2022-03-22 15:19:44,155 INFO    MainThread:91914 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 825
}

2022-03-22 15:19:44,411 INFO    MainThread:91914 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 825
}

2022-03-22 15:19:45,260 INFO    MainThread:91914 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 141573
}

2022-03-22 15:19:45,369 INFO    MainThread:91914 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 141573
}

2022-03-22 15:19:45,476 INFO    MainThread:91914 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 141573
}

2022-03-22 15:19:45,583 INFO    MainThread:91914 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 141573
  total_bytes: 141573
}

2022-03-22 15:19:45,696 INFO    MainThread:91914 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 141573
  total_bytes: 141573
}

2022-03-22 15:19:45,808 INFO    MainThread:91914 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 141573
  total_bytes: 141573
}

2022-03-22 15:19:45,914 INFO    MainThread:91914 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 141573
  total_bytes: 141573
}

2022-03-22 15:19:46,021 INFO    MainThread:91914 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 141573
  total_bytes: 141573
}

2022-03-22 15:19:46,130 INFO    MainThread:91914 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 141573
  total_bytes: 141573
}

2022-03-22 15:19:46,238 INFO    MainThread:91914 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 141573
  total_bytes: 141573
}

2022-03-22 15:19:47,242 INFO    MainThread:91914 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 141573
  total_bytes: 141573
}

2022-03-22 15:19:47,893 INFO    MainThread:91914 [wandb_run.py:_on_finish():1831] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 141573
  total_bytes: 141573
}
local_info {
}

2022-03-22 15:19:49,048 INFO    MainThread:91914 [wandb_run.py:_footer_history_summary_info():2865] rendering history
2022-03-22 15:19:49,050 INFO    MainThread:91914 [wandb_run.py:_footer_history_summary_info():2894] rendering summary
2022-03-22 15:19:49,053 INFO    MainThread:91914 [wandb_run.py:_footer_sync_info():2822] logging synced files
2022-03-22 15:19:49,055 INFO    MainThread:91914 [wandb_init.py:init():492] starting backend
2022-03-22 15:19:49,055 INFO    MainThread:91914 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2022-03-22 15:19:49,057 INFO    MainThread:91914 [backend.py:ensure_launched():219] starting backend process...
2022-03-22 15:19:49,081 INFO    MainThread:91914 [backend.py:ensure_launched():224] started backend process with pid: 93681
2022-03-22 15:19:49,083 INFO    MainThread:91914 [wandb_init.py:init():501] backend started and connected
2022-03-22 15:19:49,103 INFO    MainThread:91914 [wandb_run.py:_label_probe_notebook():947] probe notebook
2022-03-22 15:19:49,103 INFO    MainThread:91914 [wandb_run.py:_label_probe_notebook():957] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-03-22 15:19:49,103 INFO    MainThread:91914 [wandb_init.py:init():565] updated telemetry
2022-03-22 15:19:49,140 INFO    MainThread:91914 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-03-22 15:19:50,199 INFO    MainThread:91914 [wandb_run.py:_on_init():1759] communicating current version
2022-03-22 15:19:50,256 INFO    MainThread:91914 [wandb_run.py:_on_init():1763] got version response 
2022-03-22 15:19:50,257 INFO    MainThread:91914 [wandb_init.py:init():625] starting run threads in backend
2022-03-22 15:19:52,393 INFO    MainThread:91914 [wandb_run.py:_console_start():1733] atexit reg
2022-03-22 15:19:52,394 INFO    MainThread:91914 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.WRAP
2022-03-22 15:19:52,394 INFO    MainThread:91914 [wandb_run.py:_redirect():1643] Wrapping output streams.
2022-03-22 15:19:52,394 INFO    MainThread:91914 [wandb_run.py:_redirect():1667] Redirects installed.
2022-03-22 15:19:52,394 INFO    MainThread:91914 [wandb_init.py:init():664] run started, returning control to user process
2022-03-22 15:19:52,394 INFO    MainThread:91914 [wandb_watch.py:watch():47] Watching
2022-03-22 15:20:05,185 INFO    MainThread:91914 [wandb_config.py:__setitem__():153] config set batch_size = 40 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fc54e64d5b0>>
2022-03-22 15:20:05,185 INFO    MainThread:91914 [wandb_run.py:_config_callback():992] config_cb batch_size 40 None
2022-03-22 15:20:05,185 INFO    MainThread:91914 [wandb_config.py:__setitem__():153] config set epochs = 40 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fc54e64d5b0>>
2022-03-22 15:20:05,185 INFO    MainThread:91914 [wandb_run.py:_config_callback():992] config_cb epochs 40 None
2022-03-22 15:20:05,185 INFO    MainThread:91914 [wandb_config.py:__setitem__():153] config set lr = 0.0066600779315279315 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fc54e64d5b0>>
2022-03-22 15:20:05,185 INFO    MainThread:91914 [wandb_run.py:_config_callback():992] config_cb lr 0.0066600779315279315 None
2022-03-22 15:20:05,185 INFO    MainThread:91914 [wandb_config.py:__setitem__():153] config set no_cuda = False - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fc54e64d5b0>>
2022-03-22 15:20:05,185 INFO    MainThread:91914 [wandb_run.py:_config_callback():992] config_cb no_cuda False None
2022-03-22 15:20:05,185 INFO    MainThread:91914 [wandb_config.py:__setitem__():153] config set seed = 42 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fc54e64d5b0>>
2022-03-22 15:20:05,185 INFO    MainThread:91914 [wandb_run.py:_config_callback():992] config_cb seed 42 None
2022-03-22 15:20:50,452 INFO    MainThread:91914 [wandb_setup.py:_flush():75] Loading settings from /Users/AFischer/.config/wandb/settings
2022-03-22 15:20:50,452 INFO    MainThread:91914 [wandb_setup.py:_flush():75] Loading settings from /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/settings
2022-03-22 15:20:50,452 INFO    MainThread:91914 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-22 15:20:50,452 INFO    MainThread:91914 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-22 15:20:50,452 INFO    MainThread:91914 [wandb_init.py:_log_setup():405] Logging user logs to /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/run-20220322_152050-2621ebh9/logs/debug.log
2022-03-22 15:20:50,452 INFO    MainThread:91914 [wandb_init.py:_log_setup():406] Logging internal logs to /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/run-20220322_152050-2621ebh9/logs/debug-internal.log
2022-03-22 15:20:50,452 INFO    MainThread:91914 [wandb_init.py:_jupyter_setup():355] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fc51e20dc70>
2022-03-22 15:20:50,453 INFO    MainThread:91914 [wandb_init.py:init():439] calling init triggers
2022-03-22 15:20:50,453 INFO    MainThread:91914 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {}
2022-03-22 15:20:50,453 INFO    MainThread:91914 [wandb_init.py:init():458] re-initializing run, found existing run on stack: jj9jhchn
2022-03-22 15:20:50,454 INFO    MainThread:91914 [wandb_run.py:finish():1539] finishing run afischer/tcn_samp_en-project/jj9jhchn
2022-03-22 15:20:50,455 INFO    MainThread:91914 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 0
2022-03-22 15:20:50,456 INFO    MainThread:91914 [wandb_run.py:_restore():1674] restore
2022-03-22 15:20:52,199 INFO    MainThread:91914 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 825
}

2022-03-22 15:20:52,310 INFO    MainThread:91914 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 825
}

2022-03-22 15:20:52,503 INFO    MainThread:91914 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 111299
}

2022-03-22 15:20:52,609 INFO    MainThread:91914 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 111299
}

2022-03-22 15:20:52,716 INFO    MainThread:91914 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 111299
}

2022-03-22 15:20:52,822 INFO    MainThread:91914 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 111299
}

2022-03-22 15:20:52,930 INFO    MainThread:91914 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 111299
  total_bytes: 111299
}

2022-03-22 15:20:53,039 INFO    MainThread:91914 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 111299
  total_bytes: 111299
}

2022-03-22 15:20:53,145 INFO    MainThread:91914 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 111299
  total_bytes: 111299
}

2022-03-22 15:20:53,252 INFO    MainThread:91914 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 111299
  total_bytes: 111299
}

2022-03-22 15:20:53,362 INFO    MainThread:91914 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 111299
  total_bytes: 111299
}

2022-03-22 15:20:53,472 INFO    MainThread:91914 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 111299
  total_bytes: 111299
}

2022-03-22 15:20:53,579 INFO    MainThread:91914 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 111299
  total_bytes: 111299
}

2022-03-22 15:20:54,669 INFO    MainThread:91914 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 111299
  total_bytes: 111299
}

2022-03-22 15:20:55,141 INFO    MainThread:91914 [wandb_run.py:_on_finish():1831] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 111299
  total_bytes: 111299
}
local_info {
}

2022-03-22 15:20:56,287 INFO    MainThread:91914 [wandb_run.py:_footer_history_summary_info():2865] rendering history
2022-03-22 15:20:56,289 INFO    MainThread:91914 [wandb_run.py:_footer_history_summary_info():2894] rendering summary
2022-03-22 15:20:56,293 INFO    MainThread:91914 [wandb_run.py:_footer_sync_info():2822] logging synced files
